package:
  name: nxp_fixelf
  version: "0.1"

source:
  url: https://www.nxp.com/lgfiles/updates/mcuxpresso/MCUX-fixelf-windows.zip # [win]
  sha256: 7e8220b202463db910d856076a6d269d11cd23ba996cdda8c0ef6e9714d4e08e # [win]]
  url: https://www.nxp.com/lgfiles/updates/mcuxpresso/MCUX-fixelf-linux.tar.xz # [linux64]
  sha256: eb7c2c949d217f922aeea4a5a64d1374c0d9899ba4343ed11a22492ab6d8d9b9 # [linux64]
  url: https://www.nxp.com/lgfiles/updates/mcuxpresso/MCUX-fixelf-macos.tar.xz # [macos]
  sha256: eb7c2c949d217f922aeea4a5a64d1374c0d9899ba4343ed11a22492ab6d8d9b9 # [macos]
 
build:
  string: '0'

about:
  home: https://www.nxp.com
  license: NXP
  summary: Additional NXP libraries and header files for Arm GNU Toolchain.
  