package:
  name: nxp fixelf
  version: "12.2.rel1"

source:
  url: https://www.nxp.com/lgfiles/updates/mcuxpresso/AdditionalCLibs-12.2.1-win32.zip # [win]
  sha256: a733135708418bda29bcd4f5e3247fea83c4012d4a3c2704fc966696b99a1b4f # [win]]
  url: https://www.nxp.com/lgfiles/updates/mcuxpresso/AdditionalCLibs-12.2.1-linux.tar.xz # [linux64]
  sha256: fbf00b2ede5e230f2d8cecb13545fb501aec62eb5e813294e9dbdff194745b2b # [linux64]
  
build:
  string: '0'

test:
  commands:
    - arm-none-eabi-gcc --version

about:
  home: https://www.nxp.com
  license: NXP
  summary: Additional NXP libraries and header files for Arm GNU Toolchain.
  