package:
  name: ninja
  version: "1.11.11"

source:
  url: https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip # [win]
  sha256: 524b344a1a9a55005eaf868d991e090ab8ce07fa109f1820d40e74642e289abc # [win]
  url: https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip # [linux64]
  sha256: b901ba96e486dce377f9a070ed4ef3f79deb45f4ffe2938f8e7ddc69cfb3df77 # [linux64]
  url: https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-mac.zip # [osx]
  sha256: 482ecb23c59ae3d4f158029112de172dd96bb0e97549c4b1ca32d8fad11f873e # [osx]]

build:
  string: "0"

test:
  commands:
    - ninja --version

about:
  home: https://ninja-build.org/
  license: Apache-2.0
  summary: Ninja
  